name: Deploy Backend to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /var/www/fointer/Fointer-backend
            git pull origin main
            npm ci --omit=dev
            pm2 restart Fointer-backend --update-env